// <auto-generated />
using System;
using EnterpriseIntegrationHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnterpriseIntegrationHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnterpriseIntegrationHubDbContext))]
    [Migration("20260802101858_SyncWorkflowModelSnapshot")]
    partial class SyncWorkflowModelSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnterpriseIntegrationHub.Domain.Entities.Connector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AuthenticationType")
                        .HasColumnType("int");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ExternalSystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("Protocol")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSystemId");

                    b.HasIndex("Name", "ExternalSystemId")
                        .IsUnique()
                        .HasDatabaseName("IX_Connectors_Name_ExternalSystemId");

                    b.ToTable("Connectors", (string)null);
                });

            modelBuilder.Entity("EnterpriseIntegrationHub.Domain.Entities.ExternalSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Environment")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Environment")
                        .IsUnique()
                        .HasDatabaseName("IX_ExternalSystems_Name_Environment");

                    b.ToTable("ExternalSystems", (string)null);
                });

            modelBuilder.Entity("EnterpriseIntegrationHub.Domain.Entities.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<Guid>("SourceConnectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TriggerEvent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Workflows_Name");

                    b.HasIndex("SourceConnectorId");

                    b.ToTable("Workflows", (string)null);
                });

            modelBuilder.Entity("EnterpriseIntegrationHub.Domain.Entities.WorkflowStep", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("DestinationConnectorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WorkflowId", "ExecutionOrder");

                    b.HasIndex("DestinationConnectorId");

                    b.ToTable("WorkflowSteps", (string)null);
                });

            modelBuilder.Entity("EnterpriseIntegrationHub.Domain.Entities.Connector", b =>
                {
                    b.HasOne("EnterpriseIntegrationHub.Domain.Entities.ExternalSystem", null)
                        .WithMany()
                        .HasForeignKey("ExternalSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnterpriseIntegrationHub.Domain.Entities.Workflow", b =>
                {
                    b.HasOne("EnterpriseIntegrationHub.Domain.Entities.Connector", null)
                        .WithMany()
                        .HasForeignKey("SourceConnectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EnterpriseIntegrationHub.Domain.Entities.WorkflowStep", b =>
                {
                    b.HasOne("EnterpriseIntegrationHub.Domain.Entities.Connector", null)
                        .WithMany()
                        .HasForeignKey("DestinationConnectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnterpriseIntegrationHub.Domain.Entities.Workflow", null)
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnterpriseIntegrationHub.Domain.Entities.Workflow", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
